name: Daily price fetch

on:
  workflow_dispatch: {}          # allows a manual "Run workflow" button
  schedule:
    - cron: "15 16 * * *"        # runs daily at 16:15 UTC (~18:15 SAST)

permissions:
  contents: write                # needed to push commits with GITHUB_TOKEN

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"           # speed up pip installs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tracker
        run: |
          python price_tracker.py --cards cards.txt --db prices.db --csv prices_latest.csv

      - name: Commit updated artifacts
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add prices.db prices_latest.csv || true
          git commit -m "chore: daily fetch" || echo "No changes to commit"
          git push
